import { Footer } from "./components/Footer";
import { Header } from "./components/Header";

import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["300"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Hello Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body className={roboto.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
