import { Footer } from "./components/Footer";
import { Header } from "./components/Header";

export const metadata = {
  title: "Hello Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
